// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHA4lBgXNIkjfw-mCX7l2UB5gIb7ITCKo',
    appId: '1:206785201758:web:34de839f03cd91de8096cf',
    messagingSenderId: '206785201758',
    projectId: 'sara777-9bbe4',
    authDomain: 'sara777-9bbe4.firebaseapp.com',
    storageBucket: 'sara777-9bbe4.firebasestorage.app',
    measurementId: 'G-0NYW98H8L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhWFpjKohmPn9_CpvCp4UEt25PVw7x-8',
    appId: '1:206785201758:android:dabce8d8f35a6e208096cf',
    messagingSenderId: '206785201758',
    projectId: 'sara777-9bbe4',
    storageBucket: 'sara777-9bbe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrFQhXg2mui-nKCJ400Zlyn5gZsfXrzyY',
    appId: '1:206785201758:ios:decd50a722f53c4e8096cf',
    messagingSenderId: '206785201758',
    projectId: 'sara777-9bbe4',
    storageBucket: 'sara777-9bbe4.firebasestorage.app',
    iosBundleId: 'com.sara777.newSara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrFQhXg2mui-nKCJ400Zlyn5gZsfXrzyY',
    appId: '1:206785201758:ios:decd50a722f53c4e8096cf',
    messagingSenderId: '206785201758',
    projectId: 'sara777-9bbe4',
    storageBucket: 'sara777-9bbe4.firebasestorage.app',
    iosBundleId: 'com.sara777.newSara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHA4lBgXNIkjfw-mCX7l2UB5gIb7ITCKo',
    appId: '1:206785201758:web:b6bd44888694586d8096cf',
    messagingSenderId: '206785201758',
    projectId: 'sara777-9bbe4',
    authDomain: 'sara777-9bbe4.firebaseapp.com',
    storageBucket: 'sara777-9bbe4.firebasestorage.app',
    measurementId: 'G-D3Z2NZ44SV',
  );
}
